version: '3.8'

services:

  postgresql:
    image: docker.io/bitnami/postgresql:13
    environment:
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=bitnami_sonarqube
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    expose:
      - "5423"

  sonar:
    image: docker.io/bitnami/sonarqube:latest
    depends_on:
      - postgresql
    environment:
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=password
    ports:
      - "81:9000"
    volumes:
      - "sonarqube_data:/bitnami/sonarqube"

  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/jenkins:lts
    environment:
      JENKINS_ADMIN_ID: "user"
      JENKINS_ADMIN_PASSWORD: "password"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"

volumes:
  postgresql_data:
  sonarqube_data:
  jenkins_home: