version: "3"

services:
  app:
    image: my-app
    build: flask
    container_name: flask
    restart: always
    ports:
      - 81:8000
    depends_on:
      - redis
    environment:
      - REDIS_PORT=6379
      - REDIS_HOSTNAME=redis
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - app:/data
volumes:
  app: